-- ============================================================
-- PenTest Agent — Supabase Schema
-- Run this in the Supabase SQL Editor to set up all tables.
-- ============================================================


-- ── users ────────────────────────────────────────────────────
-- Extends auth.users with app-specific profile data.
create table public.users (
  id            uuid primary key references auth.users(id) on delete cascade,
  username      text not null,
  github_token  text,
  created_at    timestamptz default now()
);

alter table public.users enable row level security;

create policy "users: select own"   on public.users for select using (auth.uid() = id);
create policy "users: insert own"   on public.users for insert with check (auth.uid() = id);
create policy "users: update own"   on public.users for update using (auth.uid() = id);


-- ── scans ────────────────────────────────────────────────────
-- One row per scan initiated by a user.
create table public.scans (
  id             uuid primary key default gen_random_uuid(),
  user_id        uuid not null references auth.users(id) on delete cascade,
  target_url     text not null,
  status         text not null default 'CRAWLING'
                   check (status in ('CRAWLING','SCANNING','AWAITING_APPROVAL','EXPLOITING','DONE','ERROR')),
  surface_report jsonb,          -- SurfaceReport blob (urls, forms, headers, tech stack, etc.)
  report_pdf_url text,           -- Supabase Storage signed URL for the generated PDF
  error          text,
  created_at     timestamptz default now(),
  updated_at     timestamptz default now()
);

alter table public.scans enable row level security;

create policy "scans: select own"  on public.scans for select using (auth.uid() = user_id);
create policy "scans: insert own"  on public.scans for insert with check (auth.uid() = user_id);
create policy "scans: update own"  on public.scans for update using (auth.uid() = user_id);
create policy "scans: delete own"  on public.scans for delete using (auth.uid() = user_id);

-- Auto-update updated_at on every write
create or replace function update_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger scans_updated_at
  before update on public.scans
  for each row execute function update_updated_at();


-- ── hypotheses ───────────────────────────────────────────────
-- Attack hypotheses generated by the Recon Agent for a scan.
create table public.hypotheses (
  id                text not null,
  scan_id           uuid not null references public.scans(id) on delete cascade,
  title             text not null,
  target_url        text,
  attack_surface    text,
  technique         text,
  attack_hints      text,
  rationale         text,
  severity_estimate text not null default 'MEDIUM'
                      check (severity_estimate in ('CRITICAL','HIGH','MEDIUM','LOW','INFO')),
  primary key (id, scan_id)
);

alter table public.hypotheses enable row level security;

create policy "hypotheses: select via scan owner"
  on public.hypotheses for select
  using (
    exists (
      select 1 from public.scans
      where scans.id = hypotheses.scan_id
        and scans.user_id = auth.uid()
    )
  );

create policy "hypotheses: insert via scan owner"
  on public.hypotheses for insert
  with check (
    exists (
      select 1 from public.scans
      where scans.id = hypotheses.scan_id
        and scans.user_id = auth.uid()
    )
  );


-- ── agent_results ────────────────────────────────────────────
-- Exploit agent result for each hypothesis.
create table public.agent_results (
  id                    uuid primary key default gen_random_uuid(),
  scan_id               uuid not null references public.scans(id) on delete cascade,
  hypothesis_id         text not null,
  hypothesis_title      text,
  technique             text,
  status                text not null default 'PENDING'
                          check (status in ('PENDING','RUNNING','CONFIRMED','UNCONFIRMED','ERROR')),
  severity              text not null default 'INFO'
                          check (severity in ('CRITICAL','HIGH','MEDIUM','LOW','INFO')),
  steps                 jsonb default '[]',   -- list[ExploitStep]
  summary               text,
  remediation           text,
  cvss_score            float8,
  screenshot_paths      text[] default '{}',
  false_positive_reason text,
  created_at            timestamptz default now()
);

alter table public.agent_results enable row level security;

create policy "agent_results: select via scan owner"
  on public.agent_results for select
  using (
    exists (
      select 1 from public.scans
      where scans.id = agent_results.scan_id
        and scans.user_id = auth.uid()
    )
  );

create policy "agent_results: insert via scan owner"
  on public.agent_results for insert
  with check (
    exists (
      select 1 from public.scans
      where scans.id = agent_results.scan_id
        and scans.user_id = auth.uid()
    )
  );

create policy "agent_results: update via scan owner"
  on public.agent_results for update
  using (
    exists (
      select 1 from public.scans
      where scans.id = agent_results.scan_id
        and scans.user_id = auth.uid()
    )
  );


-- ── scan_events ──────────────────────────────────────────────
-- Live SSE events persisted for history / reconnect.
create table public.scan_events (
  id         bigserial primary key,
  scan_id    uuid not null references public.scans(id) on delete cascade,
  event      text not null,
  data       jsonb not null,
  created_at timestamptz default now()
);

alter table public.scan_events enable row level security;

create policy "scan_events: select via scan owner"
  on public.scan_events for select
  using (
    exists (
      select 1 from public.scans
      where scans.id = scan_events.scan_id
        and scans.user_id = auth.uid()
    )
  );

create policy "scan_events: insert via scan owner"
  on public.scan_events for insert
  with check (
    exists (
      select 1 from public.scans
      where scans.id = scan_events.scan_id
        and scans.user_id = auth.uid()
    )
  );


-- ── Storage bucket for screenshots ───────────────────────────
-- Creates a private 'screenshots' bucket (max 10 MB per file).
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'screenshots',
  'screenshots',
  false,
  10485760,   -- 10 MB
  array['image/png', 'image/jpeg', 'image/webp']
)
on conflict (id) do nothing;

create policy "screenshots: upload own"
  on storage.objects for insert
  with check (
    bucket_id = 'screenshots'
    and auth.uid()::text = (storage.foldername(name))[1]
  );

create policy "screenshots: read own"
  on storage.objects for select
  using (
    bucket_id = 'screenshots'
    and auth.uid()::text = (storage.foldername(name))[1]
  );


-- ── Storage bucket for PDF reports ───────────────────────────
-- Creates a private 'reports' bucket (max 50 MB per file).
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'reports',
  'reports',
  false,
  52428800,   -- 50 MB
  array['application/pdf']
)
on conflict (id) do nothing;

create policy "reports: upload service"
  on storage.objects for insert
  with check (bucket_id = 'reports');

create policy "reports: read own"
  on storage.objects for select
  using (
    bucket_id = 'reports'
    and auth.uid()::text = (storage.foldername(name))[1]
  );
